version: '3'

services:
  api-gateway:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run app-1:dev:docker
    ports:
      - 9999:3000

volumes:
  mono-node-modules: null