version: '3'

services:
  api-gateway:
    container_name: api-gateway
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run serve:api-gateway
    ports:
      - 9999:3000
    depends_on:
      - zookeeper
      - kafka

  auth-service:
    container_name: auth-service
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run serve:auth-service
    depends_on:
      - api-gateway

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8989:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

volumes:
  mono-node-modules: null